-- Run this once in Supabase SQL Editor.
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  price integer not null check (price > 0),
  image_url text,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

alter table public.cart_items enable row level security;

create policy "Customers can view their own cart"
  on public.cart_items for select
  using (auth.uid() = user_id);

create policy "Customers can add to their own cart"
  on public.cart_items for insert
  with check (auth.uid() = user_id);

create policy "Customers can update their own cart"
  on public.cart_items for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Customers can remove their own cart items"
  on public.cart_items for delete
  using (auth.uid() = user_id);
